### ISSUE TITLE
Traceback (most recent call last):   File "/home/yan/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 696, in __del__ TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by yanqswhu** [QLaboratory/QlabChallengerRepo#2]

**Comment by yanqswhu** [comment]
https://gist.github.com/fchollet/f35fbc80e066a49d65f1688a7e99f069

**Comment by yanqswhu** [comment]
https://stackoverflow.com/questions/40560795/tensorflow-attributeerror-nonetype-object-has-no-attribute-tf-deletestatus

**Comment by DragonEmperorG** [comment]
You can run import gc; gc.collect() in the end of your code.
